TEXTURE(albedo, 0)

struct Vert {
    vec4 color;
    vec2 position;
    float time;
    float pad;
};

struct Frag {
    vec4 color;
    vec2 position;
};

Frag vert(Vert vert) {
    Frag frag;
    float s = sin(get_global().time * 2 * 0.5f + 0.5f);
    frag.color = vert.color;
    frag.position = vert.position + vec2(s, 0);
    return frag;
}

vec4 frag(vec3 coords, Frag v1, Frag v2, Frag v3) {
    vec4 uv = coords.x * v1.color + coords.y * v2.color + coords.z * v3.color;
    return vec4(uv.x, uv.y, uv.z, 1);
}
